name: CI/CD Pipeline

on: 
  push:
    branches: 
      - test
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
  
      - name: Compile CUDA program
        run: nvcc test.cu -o test.out
  
      - name: Run tests
        run: ./test.out
