name: CI/CD Pipeline

on: 
  push:
    branches: 
      - test

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y wget gnupg2

      - name: Add NVIDIA package repository
        run: |
          wget https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2204/x86_64/cuda-keyring_1.1-1_all.deb
          sudo dpkg -i cuda-keyring_1.1-1_all.deb
          sudo apt-get update

      - name: Install CUDA
        run: |
          sudo apt-get install -y cuda

      - name: Set up PATH for CUDA
        run: echo "/usr/local/cuda/bin" >> $GITHUB_PATH

      - name: Compile CUDA program
        run: nvcc test.cu -o test.out

      - name: Run tests
        run: ./test.out
